@startuml

interface I1inchRouter {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+💰unoswap()

}


class Exploit_Wintermute {
    ' -- inheritance --
	{abstract}TestHarness
	{abstract}TokenBalanceTracker

    ' -- usingFor --

    ' -- vars --
	#[[address]] attacker
	#[[address]] attackerContractAddr
	#[[address]] wintermute
	#[[IWETH9]] weth
	#[[I1inchRouter]] inchRouter

    ' -- methods --
	+setUp()
	+test_attack()

}
' -- inheritance / usingFor --
Exploit_Wintermute --[#DarkGoldenRod]|> TestHarness
Exploit_Wintermute --[#DarkGoldenRod]|> TokenBalanceTracker

@enduml