#!/bin/bash

shopt -s nocasematch

start=$1
output=""

while [[ ! $output == *77777FeDdddFfC19Ff86DB637967013e6C6A116C* ]]
do
  output=$(cast storage 0x5efda50f22d34F262c29268506C5Fa42cB56A1Ce $start --rpc-url https://rpc.ankr.com/eth --block 17304423)
  echo "[$start] [$output]"
  
  ((start++))
done

shopt -u nocasematch

# This script looks for the slot where the torn address is located. As it is the last one of the storage stack, then by reading the source code of the tornado cash governance proxy https://vscode.blockscan.com/ethereum/0xa9689ed4a82a288e267b11ae8fe137fb4cb2177e it is possible to get the real slot for the lockedBalances mapping (will show zero data but is needed to calculate each key's slot)

# Run with one positional argument setting the slot to start from. Cast should be installed.

# chmod +x ./SlotScanner
# ./SlotScanner 50
# This will start scaninng from the slot 50.