@startuml

interface IUniswapV3Router {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+💰exactInputSingle()

}


interface IDiamondCut {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --

}


interface Ibeanstalk {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+depositBeans()
	+propose()
	+deposit()
	+vote()
	+emergencyCommit()

}


interface IAaveFlashLoan {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+flashLoan()

}


interface IAaveDebtToken {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+mintToTreasury()

}


interface ICurve {
    ' -- inheritance --
	{abstract}IERC20

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+add_liquidity()
	+add_liquidity()
	+exchange()
	+remove_liquidity_one_coin()

}


interface ICurveFactory {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+exchange()

}


class Exploit_Beanstalk {
    ' -- inheritance --
	{abstract}TestHarness
	{abstract}TokenBalanceTracker

    ' -- usingFor --

    ' -- vars --
	#[[address]] attacker
	#[[IERC20]] bean
	#[[IWETH9]] weth
	#[[Ibeanstalk]] beanstalk
	#[[IUniswapV2Router02]] router

    ' -- methods --
	+setUp()
	+test_attack()
	#swapETHforBeans()
	#deployDonationContract()
	#🔍isDeployedContract()
	+💰create2Deploy()
	+🔍precomputeAddress()

}


class IBean {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --

    ' -- methods --
	+mint()

}


class InitBip18 {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --
	-{static}[[address]] bean
	-{static}[[address]] proposerWallet
	-{static}[[address]] ukraineWallet
	-{static}[[uint256]] proposerAmount
	-{static}[[uint256]] donationAmount

    ' -- methods --
	+init()

}


class FlashLoanAttacker {
    ' -- inheritance --
	{abstract}TokenBalanceTracker

    ' -- usingFor --

    ' -- vars --
	+[[address]] tokens
	#{static}[[IERC20]] bean
	#{static}[[IERC20]] dai
	#{static}[[IERC20]] usdc
	#{static}[[IERC20]] usdt
	#{static}[[IERC20]] lusd
	#{static}[[IERC20]] curve3Crv
	#{static}[[IWETH9]] weth
	#{static}[[ICurve]] curveStablesPool
	#{static}[[ICurve]] curveFactory
	#{static}[[ICurve]] curveBeanCRV
	#{static}[[ICurve]] curveBeanLusd
	+[[address]] beanstalk
	#[[IUniswapV2Pair]] sushiLusdOhm
	#[[IUniswapV2Pair]] beanWethPair
	#[[IAaveFlashLoan]] aaveV2
	#[[IUniswapV2Router02]] routerv2
	#[[IUniswapV3Router]] routerv3
	#[[uint256]] amountsSwapped
	#[[uint256]] beanReceivedAfterSwap

    ' -- methods --
	+**__constructor__**()
	+flashLoanAave()
	+executeOperation()
	+uniswapV2Call()
	-addLiquidityToStableCurve()
	#exchangeCurveLusd()
	#addLiquidityToBeansPool()
	#addLiquidityToBeansLusdPool()
	#depositVoteExecute()
	+💰**__constructor__**()

}


class ExploitBip {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --
	-{static}[[IERC20]] beans
	-{static}[[IERC20]] beans3Crv
	-{static}[[IERC20]] beansLusd
	-{static}[[IERC20]] beansWethPair
	-{static}[[address]] beansProtocol

    ' -- methods --
	+init()

}
' -- inheritance / usingFor --
ICurve --[#DarkGoldenRod]|> IERC20
Exploit_Beanstalk --[#DarkGoldenRod]|> TestHarness
Exploit_Beanstalk --[#DarkGoldenRod]|> TokenBalanceTracker
FlashLoanAttacker --[#DarkGoldenRod]|> TokenBalanceTracker

@enduml