@startuml

class Target {
    ' -- inheritance --

    ' -- usingFor --

    ' -- vars --
	+{static}[[IERC20]] token
	-{static}[[ICurve]] pool
	+[[mapping address=>uint ]] balanceOf

    ' -- methods --
	+stake()
	+unstake()
	+🔍getReward()

}


class Exploit_ReadOnly {
    ' -- inheritance --
	{abstract}TestHarness

    ' -- usingFor --

    ' -- vars --
	#[[AttackerContract]] attackerContract
	#[[Target]] target
	#[[address]] attacker

    ' -- methods --
	+setUp()
	+test_attack()

}


class AttackerContract {
    ' -- inheritance --
	{abstract}TestHarness

    ' -- usingFor --

    ' -- vars --
	-{static}[[ICurve]] pool
	+{static}[[IERC20]] lpToken
	-[[Target]] target

    ' -- methods --
	+**__constructor__**()
	+💰**__constructor__**()
	+💰setup()
	+💰pwn()

}
' -- inheritance / usingFor --
Exploit_ReadOnly --[#DarkGoldenRod]|> TestHarness
AttackerContract --[#DarkGoldenRod]|> TestHarness

@enduml