Nomad {
    Moonbeam {
        mb-deposit: Deposit 0.1 WBTC
    }

    Mainnet {
        payload: getPayload()
        process: process()
    }
  }
  
  Attacker -> Nomad.Moonbeam.mb-deposit: 1°
  Attacker -> Nomad.Mainnet.payload: 2°
  Attacker -> Nomad.Mainnet.process: 3°

  
  explanation: |md
    # Nomad
    - Decentralized attack
    - Reproduceable just by copying payload
  |
  